version: '3.8'

services:
  # Redis 서버 (오더북 매칭 엔진용)
  redis:
    image: redis:7-alpine
    container_name: hyperindex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-hyperindex_secure_password}
    restart: unless-stopped
    networks:
      - hyperindex-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-hyperindex_secure_password}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Redis Commander (Redis GUI 관리 도구)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hyperindex-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-hyperindex_secure_password}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - hyperindex-network

  # Redis Insight (고급 Redis 모니터링 도구)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: hyperindex-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - hyperindex-network

volumes:
  redis_data:
    driver: local
  redis_insight_data:
    driver: local

networks:
  hyperindex-network:
    driver: bridge